// Package targets provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package targets

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for DeleteTargetRequestDataType.
const (
	DeleteTargetRequestDataTypeTarget DeleteTargetRequestDataType = "target"
)

// Defines values for TargetRelationshipsOrganizationDataType.
const (
	Organization TargetRelationshipsOrganizationDataType = "organization"
)

// Defines values for TargetType.
const (
	TargetTypeTarget TargetType = "target"
)

// DeleteTargetRequest defines model for DeleteTargetRequest.
type DeleteTargetRequest struct {
	Data struct {
		Type DeleteTargetRequestDataType `json:"type"`
	} `json:"data"`
}

// DeleteTargetRequestDataType defines model for DeleteTargetRequest.Data.Type.
type DeleteTargetRequestDataType string

// Error defines model for Error.
type Error struct {
	Errors []struct {
		Detail string  `json:"detail"`
		Status string  `json:"status"`
		Title  *string `json:"title,omitempty"`
	} `json:"errors"`
}

// Target defines model for Target.
type Target struct {
	Attributes struct {
		// Created When the target was created
		Created *time.Time `json:"created,omitempty"`

		// DisplayName Human-readable name for the target
		DisplayName string `json:"display_name"`

		// Origin Source of the target (e.g., github, gitlab, cli)
		Origin string `json:"origin"`

		// Url URL of the target repository or registry
		Url string `json:"url"`
	} `json:"attributes"`

	// Id Target ID
	Id            openapi_types.UUID `json:"id"`
	Relationships *struct {
		Organization *struct {
			Data *struct {
				Id   *openapi_types.UUID                      `json:"id,omitempty"`
				Type *TargetRelationshipsOrganizationDataType `json:"type,omitempty"`
			} `json:"data,omitempty"`
		} `json:"organization,omitempty"`
	} `json:"relationships,omitempty"`
	Type TargetType `json:"type"`
}

// TargetRelationshipsOrganizationDataType defines model for Target.Relationships.Organization.Data.Type.
type TargetRelationshipsOrganizationDataType string

// TargetType defines model for Target.Type.
type TargetType string

// TargetList defines model for TargetList.
type TargetList struct {
	Data  []Target `json:"data"`
	Links *struct {
		Next *string `json:"next,omitempty"`
		Prev *string `json:"prev,omitempty"`
		Self *string `json:"self,omitempty"`
	} `json:"links,omitempty"`
}

// TargetResponse defines model for TargetResponse.
type TargetResponse struct {
	Data Target `json:"data"`
}

// ListTargetsParams defines parameters for ListTargets.
type ListTargetsParams struct {
	// Limit Number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Cursor for pagination
	StartingAfter *string `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// Origin Filter by origin (e.g., github, gitlab, cli)
	Origin *string `form:"origin,omitempty" json:"origin,omitempty"`
}

// DeleteTargetApplicationVndAPIPlusJSONRequestBody defines body for DeleteTarget for application/vnd.api+json ContentType.
type DeleteTargetApplicationVndAPIPlusJSONRequestBody = DeleteTargetRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListTargets request
	ListTargets(ctx context.Context, orgId openapi_types.UUID, params *ListTargetsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTargetWithBody request with any body
	DeleteTargetWithBody(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteTargetWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, body DeleteTargetApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTarget request
	GetTarget(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListTargets(ctx context.Context, orgId openapi_types.UUID, params *ListTargetsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTargetsRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTargetWithBody(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTargetRequestWithBody(c.Server, orgId, targetId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTargetWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, body DeleteTargetApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTargetRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, targetId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTarget(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTargetRequest(c.Server, orgId, targetId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListTargetsRequest generates requests for ListTargets
func NewListTargetsRequest(server string, orgId openapi_types.UUID, params *ListTargetsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/targets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartingAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "starting_after", runtime.ParamLocationQuery, *params.StartingAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Origin != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "origin", runtime.ParamLocationQuery, *params.Origin); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteTargetRequestWithApplicationVndAPIPlusJSONBody calls the generic DeleteTarget builder with application/vnd.api+json body
func NewDeleteTargetRequestWithApplicationVndAPIPlusJSONBody(server string, orgId openapi_types.UUID, targetId openapi_types.UUID, body DeleteTargetApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteTargetRequestWithBody(server, orgId, targetId, "application/vnd.api+json", bodyReader)
}

// NewDeleteTargetRequestWithBody generates requests for DeleteTarget with any type of body
func NewDeleteTargetRequestWithBody(server string, orgId openapi_types.UUID, targetId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "target_id", runtime.ParamLocationPath, targetId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/targets/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTargetRequest generates requests for GetTarget
func NewGetTargetRequest(server string, orgId openapi_types.UUID, targetId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "target_id", runtime.ParamLocationPath, targetId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/targets/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListTargetsWithResponse request
	ListTargetsWithResponse(ctx context.Context, orgId openapi_types.UUID, params *ListTargetsParams, reqEditors ...RequestEditorFn) (*ListTargetsResponse, error)

	// DeleteTargetWithBodyWithResponse request with any body
	DeleteTargetWithBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteTargetResponse, error)

	DeleteTargetWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, body DeleteTargetApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteTargetResponse, error)

	// GetTargetWithResponse request
	GetTargetWithResponse(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetTargetResponse, error)
}

type ListTargetsResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *TargetList
	ApplicationvndApiJSON401 *Error
	ApplicationvndApiJSON404 *Error
	ApplicationvndApiJSON500 *Error
}

// Status returns HTTPResponse.Status
func (r ListTargetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTargetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteTargetResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON401 *Error
	ApplicationvndApiJSON404 *Error
	ApplicationvndApiJSON500 *Error
}

// Status returns HTTPResponse.Status
func (r DeleteTargetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTargetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTargetResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *TargetResponse
	ApplicationvndApiJSON401 *Error
	ApplicationvndApiJSON404 *Error
	ApplicationvndApiJSON500 *Error
}

// Status returns HTTPResponse.Status
func (r GetTargetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTargetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListTargetsWithResponse request returning *ListTargetsResponse
func (c *ClientWithResponses) ListTargetsWithResponse(ctx context.Context, orgId openapi_types.UUID, params *ListTargetsParams, reqEditors ...RequestEditorFn) (*ListTargetsResponse, error) {
	rsp, err := c.ListTargets(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTargetsResponse(rsp)
}

// DeleteTargetWithBodyWithResponse request with arbitrary body returning *DeleteTargetResponse
func (c *ClientWithResponses) DeleteTargetWithBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteTargetResponse, error) {
	rsp, err := c.DeleteTargetWithBody(ctx, orgId, targetId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTargetResponse(rsp)
}

func (c *ClientWithResponses) DeleteTargetWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, body DeleteTargetApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteTargetResponse, error) {
	rsp, err := c.DeleteTargetWithApplicationVndAPIPlusJSONBody(ctx, orgId, targetId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTargetResponse(rsp)
}

// GetTargetWithResponse request returning *GetTargetResponse
func (c *ClientWithResponses) GetTargetWithResponse(ctx context.Context, orgId openapi_types.UUID, targetId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetTargetResponse, error) {
	rsp, err := c.GetTarget(ctx, orgId, targetId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTargetResponse(rsp)
}

// ParseListTargetsResponse parses an HTTP response from a ListTargetsWithResponse call
func ParseListTargetsResponse(rsp *http.Response) (*ListTargetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTargetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TargetList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseDeleteTargetResponse parses an HTTP response from a DeleteTargetWithResponse call
func ParseDeleteTargetResponse(rsp *http.Response) (*DeleteTargetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTargetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseGetTargetResponse parses an HTTP response from a GetTargetWithResponse call
func ParseGetTargetResponse(rsp *http.Response) (*GetTargetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTargetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TargetResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY224bNxN+FYL/f5Gga0l23IvqLucaSJPATlCgsRFQu6PVxFxyMxy6UQy9e0FydVza",
	"MtI0SNEABrRLcme+OX3D8bUsbdNaA4adHF9LV86gUfHxCWhgeKOoBj6Fjx4ch+WWbAvECPFQpVj1V3ne",
	"QvgF4xs5fic5CpEXRbcjHROaWi4WhST46JGgiufC7vqUnXyAknunos7+qUI+JbLURwNhOT4hQ+MyRgAr",
	"1GvgK3iFdKzYu+wWI2vI7Oyg7SQUSy054N2CIlLznoAOfu67FJy+QYqZcOIZMsaWBIqD5GC3KwlbRmvk",
	"WP4+AyN4BiJFS/ypnFgeLuTUUqNYjoP34YCxAVn0fVKha7Wavzeqgb6GX32jzAGBqtREgwiHxNTShtKc",
	"TEtYo+lLO7OeShB2ugn6HgzqQSFq5JmfxF+tJoUoNd7Pyfak+4Lfnr7YkUrQWodsaS4sCYIaHdN80yue",
	"UO7L7i3nJN0r63LRxUyQUsTFyZMt5R6rnHUEWoXv3AzbTCZYqpXBzyqJvltlJ0x7Ne8SwJaqLA30S37v",
	"SvHFPLMGXWzWys0l9gJvI78VrfyfYCrH8n/DNakOO0YddrXaq/ZCajSXmfAY+MTbzs7lWCFbgqu7nHOg",
	"p/vPLb6YfZedwrXWOLjZW3dx0t10RqNKT8jzsyAg6XkEioAeep6Ft0l8e7a0me0lGFmkPhdkpf21H2bM",
	"rVwE0Wimtl+Av6HBRmnxqgXz8PWJcC2UkcTOzPxSJPxOPHx9Mjg352b5TtASODAsXGKt0homq9fMguAC",
	"t4R1hQZWLBPWzw3PFIuZugIxATACm9YSQyXQsE2aA4TGmijK1FH5M691xDcWwSo3Hg5Vi5Ut3cCZ+eUA",
	"7fA8+KJrZHLXAnGvMzZQ5xWQSx44Gh0dHxweHRz+8mY0Gse/PyJPt2BUi3IsHwxGgweykK3iWQzJ0FLt",
	"hteW6vdYLYapTONO1762fXwK7Mk4oYRGx5GLO1TBSiVqvAIjtjglqqf4fFLJsQwF25kSgZBqgCHcAt7t",
	"anu1IScRa+g2EbwsZOpkMkGXm2nJ5KFLJHUHUlwUu4pf+mYCFMwjcF6zE2wFRduXID56iH2mQ6GxQZab",
	"SiuYKq9Zjg9HhWzUJ2wCEx6OwlsIXnxbYUHDUAPlwDz25CxFB7eqRrN0aw6GY0WMpn6vphxrZ41nr9HP",
	"UDOQmIROGjrfno6dU9+1zNvUXoRAJSKKaXY0GsW7jzUMJmacaluNZbRyeGWqgWrxpw8uNcK13P1cFTtD",
	"5IttO19sZ24okOPR4VcHka68Gf1vjfI8s4SfoUrKj7+d8q2SMpbF1HoTYfz8DwTiRhgnhoGM0sIBXQEJ",
	"6A4W0vmmUTRfxmlJL2iE6hELqzrQhlzSyUUQkGe04XV6CGupOsMI1Se4NFoFgusumJN5Yp5tEtucwL5b",
	"Ftu8kWZUrhzyt7RepI/B8SNbzb96BuVG3cX2JSQgXvRY5fjGG3oKfSWcL0twbuq1not7L614nIDf/28x",
	"QucVS+JfxA0pLTZG0x4TFLdfYNLI70IfUPEmhlMs1/K2q/058I9S/5atezWq3JyvXQB/1Op3X6vPgXeb",
	"aaZxb0yMsbA2Z8V3FyH3kopc2cXx6PTp2ZswG3X/v0nzYjdZraYqiv3jYvFXAAAA///u57NRXRUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
