version: 2

project_name: snyk-api

builds:
  - id: snyk-api
    main: ./cmd/snyk-api/main.go
    binary: snyk-api
    ldflags:
      - "-s -w"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"

release:
  draft: false
  prerelease: false
