// Package issues provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package issues

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for IssueAttributesEffectiveSeverityLevel.
const (
	IssueAttributesEffectiveSeverityLevelCritical IssueAttributesEffectiveSeverityLevel = "critical"
	IssueAttributesEffectiveSeverityLevelHigh     IssueAttributesEffectiveSeverityLevel = "high"
	IssueAttributesEffectiveSeverityLevelLow      IssueAttributesEffectiveSeverityLevel = "low"
	IssueAttributesEffectiveSeverityLevelMedium   IssueAttributesEffectiveSeverityLevel = "medium"
)

// Defines values for IssueAttributesSeverity.
const (
	IssueAttributesSeverityCritical IssueAttributesSeverity = "critical"
	IssueAttributesSeverityHigh     IssueAttributesSeverity = "high"
	IssueAttributesSeverityLow      IssueAttributesSeverity = "low"
	IssueAttributesSeverityMedium   IssueAttributesSeverity = "medium"
)

// Defines values for IssueAttributesStatus.
const (
	IssueAttributesStatusIgnored  IssueAttributesStatus = "ignored"
	IssueAttributesStatusOpen     IssueAttributesStatus = "open"
	IssueAttributesStatusResolved IssueAttributesStatus = "resolved"
)

// Defines values for IssueAttributesType.
const (
	IssueAttributesTypeLicense IssueAttributesType = "license"
	IssueAttributesTypeVuln    IssueAttributesType = "vuln"
)

// Defines values for IssueRelationshipsOrganizationDataType.
const (
	Organization IssueRelationshipsOrganizationDataType = "organization"
)

// Defines values for IssueType.
const (
	IssueTypeIssue IssueType = "issue"
)

// Defines values for ListIssuesForOrgParamsSeverity.
const (
	Critical ListIssuesForOrgParamsSeverity = "critical"
	High     ListIssuesForOrgParamsSeverity = "high"
	Low      ListIssuesForOrgParamsSeverity = "low"
	Medium   ListIssuesForOrgParamsSeverity = "medium"
)

// Defines values for ListIssuesForOrgParamsType.
const (
	ListIssuesForOrgParamsTypeLicense ListIssuesForOrgParamsType = "license"
	ListIssuesForOrgParamsTypeVuln    ListIssuesForOrgParamsType = "vuln"
)

// Defines values for ListIssuesForOrgParamsStatus.
const (
	ListIssuesForOrgParamsStatusIgnored  ListIssuesForOrgParamsStatus = "ignored"
	ListIssuesForOrgParamsStatusOpen     ListIssuesForOrgParamsStatus = "open"
	ListIssuesForOrgParamsStatusResolved ListIssuesForOrgParamsStatus = "resolved"
)

// Error defines model for Error.
type Error struct {
	Errors []struct {
		Detail string  `json:"detail"`
		Status string  `json:"status"`
		Title  *string `json:"title,omitempty"`
	} `json:"errors"`
}

// Issue defines model for Issue.
type Issue struct {
	Attributes struct {
		Coordinates *[]struct {
			IsFixable     *bool `json:"is_fixable,omitempty"`
			IsPatchable   *bool `json:"is_patchable,omitempty"`
			IsPinnable    *bool `json:"is_pinnable,omitempty"`
			IsUpgradeable *bool `json:"is_upgradeable,omitempty"`
		} `json:"coordinates,omitempty"`

		// CreatedAt When the issue was first detected
		CreatedAt *time.Time `json:"created_at,omitempty"`

		// Description Detailed description of the issue
		Description            *string                                `json:"description,omitempty"`
		EffectiveSeverityLevel *IssueAttributesEffectiveSeverityLevel `json:"effective_severity_level,omitempty"`
		Problems               *[]struct {
			Id     *string `json:"id,omitempty"`
			Source *string `json:"source,omitempty"`
		} `json:"problems,omitempty"`

		// Severity Issue severity
		Severity IssueAttributesSeverity `json:"severity"`

		// Status Issue status
		Status *IssueAttributesStatus `json:"status,omitempty"`

		// Title Issue title
		Title string `json:"title"`

		// Type Issue type (vuln, license)
		Type IssueAttributesType `json:"type"`

		// UpdatedAt When the issue was last updated
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
	} `json:"attributes"`

	// Id Issue ID
	Id            openapi_types.UUID `json:"id"`
	Relationships *struct {
		Organization *struct {
			Data *struct {
				Id   *openapi_types.UUID                     `json:"id,omitempty"`
				Type *IssueRelationshipsOrganizationDataType `json:"type,omitempty"`
			} `json:"data,omitempty"`
		} `json:"organization,omitempty"`
		ScanItem *struct {
			Data *struct {
				Id   *openapi_types.UUID `json:"id,omitempty"`
				Type *string             `json:"type,omitempty"`
			} `json:"data,omitempty"`
		} `json:"scan_item,omitempty"`
	} `json:"relationships,omitempty"`
	Type IssueType `json:"type"`
}

// IssueAttributesEffectiveSeverityLevel defines model for Issue.Attributes.EffectiveSeverityLevel.
type IssueAttributesEffectiveSeverityLevel string

// IssueAttributesSeverity Issue severity
type IssueAttributesSeverity string

// IssueAttributesStatus Issue status
type IssueAttributesStatus string

// IssueAttributesType Issue type (vuln, license)
type IssueAttributesType string

// IssueRelationshipsOrganizationDataType defines model for Issue.Relationships.Organization.Data.Type.
type IssueRelationshipsOrganizationDataType string

// IssueType defines model for Issue.Type.
type IssueType string

// IssueList defines model for IssueList.
type IssueList struct {
	Data  []Issue `json:"data"`
	Links *struct {
		Next *string `json:"next,omitempty"`
		Prev *string `json:"prev,omitempty"`
		Self *string `json:"self,omitempty"`
	} `json:"links,omitempty"`
}

// IssueResponse defines model for IssueResponse.
type IssueResponse struct {
	Data Issue `json:"data"`
}

// ListIssuesForOrgParams defines parameters for ListIssuesForOrg.
type ListIssuesForOrgParams struct {
	// Limit Number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Cursor for pagination
	StartingAfter *string `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// Severity Filter by severity
	Severity *ListIssuesForOrgParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`

	// Type Filter by issue type
	Type *ListIssuesForOrgParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Status Filter by status
	Status *ListIssuesForOrgParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListIssuesForOrgParamsSeverity defines parameters for ListIssuesForOrg.
type ListIssuesForOrgParamsSeverity string

// ListIssuesForOrgParamsType defines parameters for ListIssuesForOrg.
type ListIssuesForOrgParamsType string

// ListIssuesForOrgParamsStatus defines parameters for ListIssuesForOrg.
type ListIssuesForOrgParamsStatus string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListIssuesForOrg request
	ListIssuesForOrg(ctx context.Context, orgId openapi_types.UUID, params *ListIssuesForOrgParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIssue request
	GetIssue(ctx context.Context, orgId openapi_types.UUID, issueId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListIssuesForOrg(ctx context.Context, orgId openapi_types.UUID, params *ListIssuesForOrgParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListIssuesForOrgRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIssue(ctx context.Context, orgId openapi_types.UUID, issueId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIssueRequest(c.Server, orgId, issueId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListIssuesForOrgRequest generates requests for ListIssuesForOrg
func NewListIssuesForOrgRequest(server string, orgId openapi_types.UUID, params *ListIssuesForOrgParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/issues", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartingAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "starting_after", runtime.ParamLocationQuery, *params.StartingAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Severity != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "severity", runtime.ParamLocationQuery, *params.Severity); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIssueRequest generates requests for GetIssue
func NewGetIssueRequest(server string, orgId openapi_types.UUID, issueId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "issue_id", runtime.ParamLocationPath, issueId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/issues/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListIssuesForOrgWithResponse request
	ListIssuesForOrgWithResponse(ctx context.Context, orgId openapi_types.UUID, params *ListIssuesForOrgParams, reqEditors ...RequestEditorFn) (*ListIssuesForOrgResponse, error)

	// GetIssueWithResponse request
	GetIssueWithResponse(ctx context.Context, orgId openapi_types.UUID, issueId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetIssueResponse, error)
}

type ListIssuesForOrgResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *IssueList
	ApplicationvndApiJSON401 *Error
	ApplicationvndApiJSON404 *Error
	ApplicationvndApiJSON500 *Error
}

// Status returns HTTPResponse.Status
func (r ListIssuesForOrgResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListIssuesForOrgResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIssueResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *IssueResponse
	ApplicationvndApiJSON401 *Error
	ApplicationvndApiJSON404 *Error
	ApplicationvndApiJSON500 *Error
}

// Status returns HTTPResponse.Status
func (r GetIssueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIssueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListIssuesForOrgWithResponse request returning *ListIssuesForOrgResponse
func (c *ClientWithResponses) ListIssuesForOrgWithResponse(ctx context.Context, orgId openapi_types.UUID, params *ListIssuesForOrgParams, reqEditors ...RequestEditorFn) (*ListIssuesForOrgResponse, error) {
	rsp, err := c.ListIssuesForOrg(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListIssuesForOrgResponse(rsp)
}

// GetIssueWithResponse request returning *GetIssueResponse
func (c *ClientWithResponses) GetIssueWithResponse(ctx context.Context, orgId openapi_types.UUID, issueId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetIssueResponse, error) {
	rsp, err := c.GetIssue(ctx, orgId, issueId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIssueResponse(rsp)
}

// ParseListIssuesForOrgResponse parses an HTTP response from a ListIssuesForOrgWithResponse call
func ParseListIssuesForOrgResponse(rsp *http.Response) (*ListIssuesForOrgResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListIssuesForOrgResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IssueList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseGetIssueResponse parses an HTTP response from a GetIssueWithResponse call
func ParseGetIssueResponse(rsp *http.Response) (*GetIssueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIssueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IssueResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYbW/bNhD+KwS3Dx2mxk7afZi/dWtTBOjWou0wYK1h0NLJvoYi1ePRjRv4vw+kJFuO",
	"qTht12LDgACR+HbPcy8PT76Wua1qa8Cwk5Nr6fIlVCo+PiGyFB5qsjUQI8RhCMPxCRkqd7igAFaowxOv",
	"a5AT6ZjQLOQmk44Ve5ecYmQNiZlNJgneeyQo5ORNd0LWWZlm3QY7fwc5x6OaAUWk1gcHtPBT+y6c83DI",
	"RzETzj1DgmtuLRVoVDs54BF0sxKv1HyP4NxaDcoEw+hmteJ8efsKNObWBb5ekCpgaM3mqKcymRMohmKm",
	"uAmkywlrRmvkRP65BCN4CQKDm8QH5USJ5FgUwJAzFDKTpaUq7JWFYrjPWIHMDkO9d+5NM49jXKEQvWFh",
	"y53l1IlQlpAzrmDmYAWEvJ5pWEFMQjC+CoHPCRlzpWUml7hYykxWUKCvZCa1/dBLiN2xNdm5biM6FNoi",
	"nejWUz6Qzkej0HE4dE7MULGdz76E3K4Wkza6Ouss2BqMDKXkrF7FYOPC2FBUqcO31Zw6u5lM7YoDA5vW",
	"NYh7K69NJjTmYBz80IMXJgLZZiaJydfFpyS3Vo5Fu+eOqX1DavZ49sKa0p4mj1LELx73rXuPRcp1BFqF",
	"bW6JdSJNLS2UwY+qq7kbiq1YDaX2Uctd0LaJ0jc1zY4XQKokXK7MLJTcVwL7GaCGK3fHvRGo6bHE2GHL",
	"+rfL4J30DB0PO2KrTN8TlHIivxvtrvRRe5+PmrstITYazWUiYQxc8b5HCWVSImF1l3UOdHl8XdLrfc9F",
	"zoN+egmutqH8B311BxfdzWKklPtQz6/C/sbML6AI6JHnZXibx7fzjjHbyyih0V68muP8zgtL5lpuwtFo",
	"SnuoB7+hwUpp8bwG8+jFhXA15KK0JF6Z9aWI8J149OLi5K15a9pXgprAgWHRwRVBKoHUHDUG9whlik5R",
	"G/lzorTeFAKNWFtPoiYbSLt47rnXOlqeiIDXTUYjVWNhc3fizPryBO3obWDZ3gDyBjZxr2URxHsF5Bpq",
	"Z+Ozh/dPz+6f/vx6PJ7Ev79CWMOto2qUE/ngZHzyQGayVryMvh5ZWrjRtaXFDIvNqEEeJhaQEPiXwJ6M",
	"E0podBwaipaqysk6J5TWW56BuDJiT8giFIrPF4WcyFCSDatzS89pEZGRqoAhNMdvbtp/3juskXQMw4GN",
	"zKRRMSEaLrKfgEwe2pRRd1C4TXbT8O++mgMFwgTOa3aCraDojQ7Eew+03qHQWCHLvtECSuU1y8npOJOV",
	"usIqyN3pOLyFaMa3LRY0DAugFJhfPTlLMWdrtQh9c+PbFAzHihjNYqZKjlWyw3OU9DlqBhLzdb9XShrZ",
	"Te+O/+ym6jYguO1iBqB0XcIBjKOtza38uz5uwMXN5KHRT2n3NtO4MEpvrMCz8bj5ODIMJhajqmuNeQz3",
	"aGWKE1Xjj+9c04vsjB9V53gRRoXc5/tsr6aDcDwcn/7jEJoP4oT5P4zyvLSEH6FojD/8dsb3lMVYbsQ7",
	"wPjpK4RhEMaFYSCjtHBAKyAB7cJMOl9VitZdmFrdTWosq0UQz+Y2d3Iatid1fnQd/4eRo5Lf/FLgQn6o",
	"eHNhifn2W3Jf1p9Co+r/WjnvfRMkLHZO+SKb36yat+1aKp0izzZ0/6+CbqhbEv+hyn4KbWGHOydm52Ep",
	"91rmWFH9ZvnNNKRdYyBVb7GLfPnk1evQQ8pMetJtw9w2oNvmkyBcEdPN3wEAAP//mwVIxdkUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
